### ISSUE TITLE
Teknoparrot UI ran into an exception (in SharpDX.SharpDXException, module SharpDX.DirectInput)

### ISSUE THREAD

**Issue by kanarbionik** [teknogods/OpenParrot#140]
Hi dear community, 

As requested in the error message itself, I am raising this issue. Here is the full text from the Exception, happening just after a program was launched from the UI. The program still starts, but controls are not working - probably as a consequence.

(((----
SharpDX.SharpDXException: HRESULT: [0x80040154], Module: [SharpDX.DirectInput], ApiCode: [DIERR_DEVICENOTREG/DeviceNotRegistered], Message: Classe non enregistrée

   at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.DirectInput.CreateDevice(Guid arg0, IntPtr& arg1, ComObject arg2)
   at SharpDX.DirectInput.Joystick..ctor(DirectInput directInput, Guid deviceGuid)
   at TeknoParrotUi.Common.InputListening.InputListenerDirectInput.ListenDirectInput(List`1 joystickButtons, GameProfile gameProfile)
   at TeknoParrotUi.Common.InputListener.<>c__DisplayClass14_0.<Listen>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---)))

![teknoparrot_ui_exception_capture](https://user-images.githubusercontent.com/84813199/119565965-e2acd680-bdaa-11eb-9efc-5d0fe0e36a52.png)

I am running Windows 10 pro 64 bits and TeknoParrotUI version 1.0.0.589. I have installed -I think- all required runtimes and libraries and my system & drivers are up to date, but the issue persists unfortunately.

My system was working fine with Windows 7, this issue happens since I upgraded to Windows 10 - not sure if directly related or not. 

Feel free to request any additional detail if needed of course. Many thanks in advance for your advices. And sorry if the question has been asked before - I did my best doing some research, unsucessfully. 

Best regards
K.

**Comment by kanarbionik** [comment]
Fixed by removing previous (backed up) files in /UserProfiles after re-reading my comment.
Sorry for the inconvenience, I am closing the issue. 
Thanks a lot for all the work.
